# Generated by Django 4.2 on 2023-06-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0006_alter_perro_sexo'),
        ('cruza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrocruza',
            name='color',
        ),
        migrations.RemoveField(
            model_name='perrocruza',
            name='fecha_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perrocruza',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='perrocruza',
            name='raza',
        ),
        migrations.RemoveField(
            model_name='perrocruza',
            name='sexo',
        ),
        migrations.AddField(
            model_name='perrocruza',
            name='perro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='perros.perro'),
            preserve_default=False,
        ),
    ]
