# Generated by Django 4.2.1 on 2023-06-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrocruza',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='', max_length=10),
        ),
    ]
