# Generated by Django 4.2.1 on 2023-06-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruza', '0002_remove_perrocruza_color_and_more'),
    ]

    operations = [
    ]
