# Generated by Django 4.2 on 2023-05-18 22:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Este campo solo puede contener caracteres.')])),
                ('raza', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Este campo solo puede contener caracteres.')])),
                ('color', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Este campo solo puede contener caracteres.')])),
                ('tamanio', models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], max_length=10)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=10)),
                ('origen', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Este campo solo puede contener caracteres.')])),
                ('observacion', models.CharField(blank=True, max_length=100)),
                ('adoptado', models.BooleanField(default=False)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
