# Generated by Django 4.2 on 2023-05-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopcion',
            old_name='tamanio',
            new_name='tamaño',
        ),
    ]
