# Generated by Django 4.2 on 2023-05-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_rename_tamanio_adopcion_tamaño'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='publicado_por',
        ),
    ]
