# Generated by Django 4.2 on 2023-05-18 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopcion', '0003_remove_adopcion_publicado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='publicado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
