# Generated by Django 4.2 on 2023-05-23 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_adopcion_publicado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='color',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\sáÁéÉíÍóÓúÚ]+$', 'Este campo solo puede contener caracteres.')]),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\sáÁéÉíÍóÓúÚ]+$', 'Este campo solo puede contener caracteres.')]),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='origen',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\sáÁéÉíÍóÓúÚ]+$', 'Este campo solo puede contener caracteres.')]),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='raza',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\sáÁéÉíÍóÓúÚ]+$', 'Este campo solo puede contener caracteres.')]),
        ),
    ]
