# Generated by Django 4.2 on 2023-05-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0005_alter_adopcion_color_alter_adopcion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='tamaño',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10),
        ),
    ]
