# Generated by Django 4.2 on 2023-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
