# Generated by Django 4.2 on 2023-05-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este telefono'}, max_length=30, unique=True),
        ),
    ]
