# Generated by Django 4.2 on 2023-05-12 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_alter_customuser_apellido_alter_customuser_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'El apellido solo debe contener caracteres.')]),
        ),
    ]
