# Generated by Django 4.2 on 2023-05-23 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_alter_customuser_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\sáÁéÉíÍóÓúÚ]+$', 'Este campo solo puede contener caracteres.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\sáÁéÉíÍóÓúÚ]+$', 'Este campo solo puede contener caracteres.')]),
        ),
    ]
