# Generated by Django 4.2.1 on 2023-05-30 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0007_alter_customuser_apellido_alter_customuser_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este DNI'}, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'El DNI solo debe contener números.')]),
        ),
    ]
