# Generated by Django 4.2 on 2023-06-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0009_alter_customuser_dni_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nuevoUsuario',
            field=models.BooleanField(default=True),
        ),
    ]
