# Generated by Django 4.2 on 2023-06-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0010_customuser_nuevousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nuevoUsuario',
        ),
    ]
