# Generated by Django 4.2 on 2023-07-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perdidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(choices=[('labrador', 'Labrador'), ('bulldog', 'Bulldog'), ('pitbull', 'Pitbull'), ('boxer', 'Boxer'), ('pastor', 'Pastor aleman'), ('beagle', 'Beagle'), ('golden', 'Golden retriever'), ('fox', 'Fox Terrier'), ('esquimal', 'Esquimal canadiense'), ('dalmata', 'Dalmata'), ('yorkshire', 'Yorkshire terrier'), ('siberiano', 'Siberiano'), ('caniche', 'Caniche'), ('chihuahua', 'Chihuahua')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('tamaño', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10)),
                ('origen', models.CharField(max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('estado', models.CharField(choices=[('Busco a su dueño', 'Busco a su dueño'), ('Perdi a mi perro', 'Perdi a mi perro')], max_length=25)),
                ('imagen', models.ImageField(upload_to='perdidos')),
            ],
        ),
    ]
