# Generated by Django 4.2 on 2023-07-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidos',
            name='imagen',
            field=models.ImageField(upload_to='perdidos/'),
        ),
    ]
