# Generated by Django 4.2 on 2023-07-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidos', '0003_alter_perdidos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidos',
            name='imagen',
            field=models.ImageField(upload_to='perdidos/'),
        ),
    ]
