# Generated by Django 4.2 on 2023-07-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidos', '0004_alter_perdidos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdidos',
            name='telefono',
            field=models.CharField(default='1', max_length=25),
        ),
    ]
