# Generated by Django 4.2 on 2023-07-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidos', '0005_perdidos_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdidos',
            name='encontrado',
            field=models.BooleanField(default=False),
        ),
    ]
