# Generated by Django 4.2.1 on 2023-06-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0003_donacion_tipo_alter_donacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
