# Generated by Django 4.2 on 2023-06-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0005_campaña_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='campana',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='donaciones.campaña'),
        ),
    ]
