# Generated by Django 4.2 on 2023-06-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0005_donacion_fecha_alter_donacion_tipo'),
        ('donaciones', '0006_donacion_campana'),
    ]

    operations = [
    ]
