# Generated by Django 4.2 on 2023-06-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0007_merge_20230617_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donaciones.campaña'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='tipo',
            field=models.CharField(choices=[('Campaña', 'Campaña'), ('Veterinaria', 'Veterinaria')], max_length=12),
        ),
    ]
