# Generated by Django 4.2 on 2023-06-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0008_alter_donacion_campana_alter_donacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='campana',
            field=models.ForeignKey(blank='', null=True, on_delete=django.db.models.deletion.CASCADE, to='donaciones.campaña'),
        ),
    ]
