# Generated by Django 4.2.1 on 2023-06-21 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0009_alter_donacion_campana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaña',
            name='monto_objetivo',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
