# Generated by Django 4.2.1 on 2023-06-21 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0010_alter_campaña_monto_objetivo_alter_donacion_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
