# Generated by Django 4.2.1 on 2023-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseadores_cuidadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paseadorcuidador',
            name='tipo',
            field=models.CharField(choices=[('P', 'Paseador'), ('C', 'Cuidador')], default='P', max_length=10),
        ),
    ]
