# Generated by Django 4.2 on 2023-05-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseadores_cuidadores', '0003_alter_paseadorcuidador_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paseadorcuidador',
            name='tipo',
            field=models.CharField(choices=[('Paseador', 'Paseador'), ('Cuidador', 'Cuidador')], default='P', max_length=10),
        ),
    ]
