# Generated by Django 4.2.1 on 2023-05-30 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseadores_cuidadores', '0004_alter_paseadorcuidador_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paseadorcuidador',
            name='dni',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este DNI'}, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'El DNI solo debe contener números.')]),
        ),
    ]
