# Generated by Django 4.2.1 on 2023-06-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseadores_cuidadores', '0009_alter_paseadorcuidador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paseadorcuidador',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
