# Generated by Django 4.2.1 on 2023-07-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paseadores_cuidadores', '0011_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='puntaje',
        ),
    ]
