# Generated by Django 4.1.7 on 2023-07-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohmydogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('nro_calle', models.IntegerField()),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
