# Generated by Django 4.2.1 on 2023-05-28 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pagos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0006_rename_cliente_asitio_turno_cliente_asistio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTarjeta', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$', 'El numero de tarjeta debe tener maximo 16 caracteres')])),
                ('nombreTitular', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\sáÁéÉíÍóÓúÚ]+$', 'Este campo solo puede contener caracteres.')])),
                ('fechaVencimiento', models.DateField(max_length=7, validators=[pagos.models.validate_fecha_vencimiento])),
                ('codigoSeguridad', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', 'El codigo de seguridad debe tener maximo 4 caracteres')])),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno')),
            ],
        ),
    ]
