# Generated by Django 4.2.1 on 2023-05-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_pago_turno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
