# Generated by Django 4.2 on 2023-06-01 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_pago_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, 'El monto a pagar debe ser mayor o igual a 1')]),
        ),
    ]
