# Generated by Django 4.2.1 on 2023-05-09 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibretaSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='perro',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.date(2023, 5, 9))),
                ('libreta_sanitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perros.libretasanitaria')),
            ],
        ),
        migrations.AddField(
            model_name='libretasanitaria',
            name='perro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perros.perro'),
        ),
    ]
