# Generated by Django 4.2.1 on 2023-05-11 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibretaSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='perro',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('libreta_sanitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perros.libretasanitaria')),
            ],
        ),
        migrations.AddField(
            model_name='libretasanitaria',
            name='perro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perros.perro'),
        ),
    ]
