# Generated by Django 4.2 on 2023-05-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_libretasanitaria_alter_perro_fecha_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libretasanitaria',
            name='perro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perros.perro'),
        ),
    ]
