# Generated by Django 4.1.7 on 2023-05-09 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_libretasanitaria_vacuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
