# Generated by Django 4.1.7 on 2023-06-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0003_alter_libretasanitaria_perro'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('labrador', 'Labrador'), ('bulldog', 'Bulldog'), ('pitbull', 'Pitbull'), ('boxer', 'Boxer'), ('pastor', 'Pastor aleman'), ('beagle', 'Beagle'), ('golden', 'Golden retriever'), ('fox', 'Fox Terrier'), ('esquimal', 'Esquimal canadiense'), ('dalmata', 'Dalmata'), ('yorkshire', 'Yorkshire terrier'), ('siberiano', 'Siberiano'), ('caniche', 'Caniche'), ('chihuahua', 'Chihuaha')], max_length=50),
        ),
    ]
