# Generated by Django 4.2 on 2023-05-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_libretasanitaria_alter_perro_fecha_de_nacimiento_and_more'),
        ('perros', '0003_alter_vacuna_fecha'),
    ]

    operations = [
    ]
