# Generated by Django 4.2 on 2023-05-10 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0004_merge_20230510_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
