# Generated by Django 4.2.1 on 2023-05-10 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0004_merge_20230510_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
