# Generated by Django 4.2.1 on 2023-06-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0006_alter_perro_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('labrador', 'Labrador'), ('bulldog', 'Bulldog'), ('pitbull', 'Pitbull'), ('boxer', 'Boxer'), ('pastor', 'Pastor aleman'), ('beagle', 'Beagle'), ('golden', 'Golden retriever'), ('fox', 'Fox Terrier'), ('esquimal', 'Esquimal canadiense'), ('dalmata', 'Dalmata'), ('yorkshire', 'Yorkshire terrier'), ('siberiano', 'Siberiano'), ('caniche', 'Caniche'), ('chihuahua', 'Chihuahua')], max_length=50),
        ),
    ]
