# Generated by Django 4.1.7 on 2023-05-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(choices=[('tarde', 'Tarde'), ('mañana', 'Mañana')], max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(choices=[('vacuna', 'Vacuna'), ('vacuna_antirrabica', 'Vacuna antirrabica'), ('desparasitacion', 'Desparasitación'), ('castracion', 'Castración'), ('urgencia', 'Urgencia'), ('consulta', 'Consulta general')], max_length=20),
        ),
    ]
