# Generated by Django 4.1.7 on 2023-05-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_estado_alter_turno_fecha_alter_turno_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='veterinario',
            new_name='cliente',
        ),
    ]
