# Generated by Django 4.1.7 on 2023-05-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_rename_veterinario_turno_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('modificado', 'Modificado')], default='pendiente', max_length=10),
        ),
    ]
