# Generated by Django 4.2 on 2023-05-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_alter_turno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='cliente_asitio',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
