# Generated by Django 4.2 on 2023-05-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_turno_cliente_asitio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='cliente_asitio',
            new_name='cliente_asistio',
        ),
    ]
